require "#{Rails.root}/db/gioco/create_badge_great_grade.rb"
require "#{Rails.root}/db/gioco/create_badge_great_grade.rb"
require "#{Rails.root}/db/gioco/create_badge_good_grade.rb"
require "#{Rails.root}/db/gioco/create_badge_great_grade.rb"
require "#{Rails.root}/db/gioco/create_badge_super great_grade.rb"
require "#{Rails.root}/db/gioco/create_badge_fever_grade.rb"
require "#{Rails.root}/db/gioco/create_badge_fever_grade.rb"
require "#{Rails.root}/db/gioco/create_badge_super great_grade.rb"
